"use client";

import { useState } from "react";
import Image from "next/image";
import { AnimatePresence, motion, useTransform, type PanInfo } from "framer-motion";
import type { CityData } from "@/lib/cityData";
import { mapImage, TICKET_SIZES, type MapVariant } from "@/lib/images";
import { TOUCH_DEVICE_QUERY, useMediaQuery } from "@/lib/useMediaQuery";
import { cardTilt } from "@/lib/deviceTilt";
import FlipCard, { TicketShine } from "./FlipCard";

const ANIMATION_OFFSET = 350;

// A swipe counts once the finger has travelled this far, or flicked this fast.
const SWIPE_DISTANCE = 80; // px
const SWIPE_VELOCITY = 400; // px/s

const slideVariants = {
  enter: (direction: number) => ({
    x: direction > 0 ? ANIMATION_OFFSET : -ANIMATION_OFFSET,
    opacity: 0,
  }),
  center: {
    zIndex: 1,
    x: 0,
    opacity: 1,
  },
  exit: (direction: number) => ({
    zIndex: 0,
    x: direction < 0 ? ANIMATION_OFFSET : -ANIMATION_OFFSET,
    opacity: 0,
  }),
};

type TicketImageProps = {
  city: CityData;
  side: "front" | "back";
  priority?: boolean;
  onLoad?: () => void;
};

const TicketImage = ({ city, side, priority, onLoad }: TicketImageProps) => {
  // The shine is masked by this image, using the URL the browser already
  // downloaded (no extra request).
  const [loadedSrc, setLoadedSrc] = useState<string | null>(null);
  return (
    <>
      <Image
        src={city.ticketImage[side]}
        alt={`${city.city} transport ticket ${side}`}
        sizes={TICKET_SIZES}
        placeholder="blur"
        loading={priority ? "eager" : undefined}
        fetchPriority={priority ? "high" : undefined}
        draggable={false}
        onLoad={(event) => {
          setLoadedSrc(event.currentTarget.currentSrc);
          onLoad?.();
        }}
        // On phones, never taller than the space between the title and controls
        // (two 74px button rows + 72px title + breathing room).
        className="h-auto max-h-[min(450px,calc(100dvh_-_260px))] w-auto max-w-full object-contain sm:max-h-[450px]"
      />
      <TicketShine src={loadedSrc} />
    </>
  );
};

type TicketProps = {
  city: CityData;
  isFirst: boolean;
  isFlipped: boolean;
  onFlip: () => void;
};

function Ticket({ city, isFirst, isFlipped, onFlip }: TicketProps) {
  // The back face is hidden until flipped, so don't let it compete for
  // bandwidth with the front: request it once the front has loaded.
  const [frontLoaded, setFrontLoaded] = useState(false);

  return (
    <FlipCard
      isFlipped={isFlipped}
      onFlip={onFlip}
      // The first city's front face is fetched right away with high priority.
      front={
        <TicketImage
          city={city}
          side="front"
          priority={isFirst}
          onLoad={() => setFrontLoaded(true)}
        />
      }
      back={frontLoaded || isFlipped ? <TicketImage city={city} side="back" /> : null}
    />
  );
}

// One theme's map. Phones get a crop of the middle of the map that covers the
// ticket stage and fades out at the sides (see globals.css); larger screens get
// the whole map. Both <Image>s are in the page and CSS shows one: the hidden
// one is display:none and lazy, so the browser never downloads it. The same
// trick on the wrapper hides the other theme's map.
// A tiny version of the map (generated by Next at build time, inlined in the
// page) shows until the map has loaded; scaled up, it reads as a soft blur.
// It's passed directly rather than as placeholder="blur": Next's blur effect
// makes the placeholder opaque, which turns the maps' transparent, faded
// edges into a grey box.
// The visible map is the largest element on screen (the LCP), hence high
// fetch priority.
function CityMap({ city, theme }: { city: CityData; theme: "light" | "dark" }) {
  const map = (variant: MapVariant, className: string) => {
    const image = mapImage(city, theme, variant);
    return (
      <Image
        {...image}
        alt=""
        fill
        placeholder={image.src.blurDataURL as `data:image/${string}`}
        loading="lazy"
        fetchPriority="high"
        // objectFit via style (not a class) so the blur placeholder is sized
        // the same way as the image.
        style={{ objectFit: variant === "mobile" ? "cover" : "contain" }}
        className={`map-fade-x pointer-events-none ${className}`}
      />
    );
  };
  return (
    <div className={`absolute inset-0 ${theme === "light" ? "dark:hidden" : "hidden dark:block"}`}>
      {map("mobile", "sm:hidden")}
      {map("desktop", "hidden sm:block")}
    </div>
  );
}

type Props = {
  city: CityData;
  direction: number;
  index: number;
  isFlipped: boolean;
  onSwipe: (step: 1 | -1) => void;
  onFlip: () => void;
};

export default function City({ city, direction, index, isFlipped, onSwipe, onFlip }: Props) {
  const isTouchDevice = useMediaQuery(TOUCH_DEVICE_QUERY);
  // Parallax: the map drifts the opposite way to the ticket's tilt (up to
  // ~15px), so the ticket looks like it floats above the city. The maps' edges
  // are faded out, so the shift never reveals an edge.
  const mapX = useTransform(cardTilt.y, (deg) => -deg * 1.5);
  const mapY = useTransform(cardTilt.x, (deg) => deg * 1.5);

  const handleDragEnd = (_: unknown, { offset, velocity }: PanInfo) => {
    if (offset.x < -SWIPE_DISTANCE || velocity.x < -SWIPE_VELOCITY) onSwipe(1);
    else if (offset.x > SWIPE_DISTANCE || velocity.x > SWIPE_VELOCITY) onSwipe(-1);
  };

  return (
    // select-none: double-clicking the ticket (to flip it twice) would
    // otherwise highlight the images as selected.
    <div className="relative flex min-h-[300px] w-full max-w-[902px] select-none flex-col items-center justify-center self-stretch overflow-hidden sm:min-h-[540px] sm:self-auto">
      {/* Both themes' maps are in the page and CSS shows the current one, so
          the right map is there on first paint (the theme class is set before
          the page renders). ImageGallery preloads the other theme's map when
          idle so a theme switch is instant; the switch itself is cross-faded
          by ThemeToggleButton. Keyed by city so a slow-loading map never
          leaves the previous city's map on screen. */}
      <motion.div aria-hidden className="absolute inset-0" style={{ x: mapX, y: mapY }}>
        <CityMap key={`${city.city}-light`} city={city} theme="light" />
        <CityMap key={`${city.city}-dark`} city={city} theme="dark" />
      </motion.div>

      {/* The ticket column fills the full height so a swipe anywhere on it
          (not only on the ticket itself) changes city. */}
      <div className="relative z-20 flex max-h-[760px] min-h-[200px] w-full max-w-[382px] flex-1 flex-col items-center justify-center px-4 sm:max-w-[350px] sm:px-0">
        <AnimatePresence initial={false} custom={direction} mode="wait">
          <motion.div
            key={index}
            custom={direction}
            variants={slideVariants}
            initial="enter"
            animate="center"
            exit="exit"
            transition={{
              x: { type: "spring", stiffness: 500, damping: 40 },
              opacity: { duration: 0.15 },
            }}
            // Swipe left/right on touch devices; vertical scrolling still works.
            drag={isTouchDevice ? "x" : false}
            dragConstraints={{ left: 0, right: 0 }}
            dragElastic={0.7}
            onDragEnd={handleDragEnd}
            className="flex w-full flex-1 items-center justify-center"
          >
            <Ticket city={city} isFirst={index === 0} isFlipped={isFlipped} onFlip={onFlip} />
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
}
