"use client";

import Image from "next/image";
import { AnimatePresence, motion, type PanInfo } from "framer-motion";
import type { CityData } from "@/lib/cityData";
import { mapImage, TICKET_SIZES, type MapVariant } from "@/lib/images";
import { TOUCH_DEVICE_QUERY, useMediaQuery } from "@/lib/useMediaQuery";
import FlipCard from "./FlipCard";

const ANIMATION_OFFSET = 350;

// Changing city: the old map fades out while the new one fades in, both
// drifting a little in the direction the ticket slides, so the map and ticket
// move as one. Runs alongside the ticket's exit and entrance (~0.45s in total).
const MAP_DRIFT = 40; // px
const mapVariants = {
  enter: (direction: number) => ({ opacity: 0, x: direction * MAP_DRIFT }),
  center: { opacity: 1, x: 0 },
  exit: (direction: number) => ({ opacity: 0, x: -direction * MAP_DRIFT }),
};

// A swipe counts once the finger has travelled this far, or flicked this fast.
const SWIPE_DISTANCE = 80; // px
const SWIPE_VELOCITY = 400; // px/s

const slideVariants = {
  enter: (direction: number) => ({
    x: direction > 0 ? ANIMATION_OFFSET : -ANIMATION_OFFSET,
    opacity: 0,
  }),
  center: {
    zIndex: 1,
    x: 0,
    opacity: 1,
  },
  // A quick, eased exit: with mode="wait" the next ticket only enters once the
  // exit has finished, and the spring used for entering took ~450ms to settle
  // while the ticket was already invisible, leaving a gap with no ticket.
  exit: (direction: number) => ({
    zIndex: 0,
    x: direction < 0 ? ANIMATION_OFFSET : -ANIMATION_OFFSET,
    opacity: 0,
    transition: { x: { duration: 0.2, ease: "easeIn" as const }, opacity: { duration: 0.15 } },
  }),
};

type TicketImageProps = {
  city: CityData;
  side: "front" | "back";
  isFirst: boolean;
};

// Both faces load eagerly: the back is hidden and rotated 180deg until flipped,
// and Safari's lazy loading doesn't reliably notice when a rotated element
// becomes visible, which could leave the back blank. Instead the back loads at
// low priority, so it doesn't compete with the front. The first city's front
// is the page's main image, so it gets high priority.
const TicketImage = ({ city, side, isFirst }: TicketImageProps) => (
  <Image
    src={city.ticketImage[side]}
    alt={`${city.city} transport ticket ${side}`}
    sizes={TICKET_SIZES}
    placeholder="blur"
    loading="eager"
    fetchPriority={side === "back" ? "low" : isFirst ? "high" : undefined}
    draggable={false}
    // On phones, never taller than the space between the title and controls
    // (two 74px button rows + 72px title + breathing room).
    className="h-auto max-h-[min(450px,calc(100dvh_-_260px))] w-auto max-w-full object-contain sm:max-h-[450px]"
  />
);

type TicketProps = {
  city: CityData;
  isFirst: boolean;
  isFlipped: boolean;
  onFlip: () => void;
};

function Ticket({ city, isFirst, isFlipped, onFlip }: TicketProps) {
  // The back is always in the page (not added once the front has loaded):
  // Safari can fail to paint content added later to a hidden, rotated layer.
  return (
    <FlipCard
      isFlipped={isFlipped}
      onFlip={onFlip}
      front={<TicketImage city={city} side="front" isFirst={isFirst} />}
      back={<TicketImage city={city} side="back" isFirst={isFirst} />}
    />
  );
}

// One theme's map. Phones get a crop of the middle of the map that covers the
// ticket stage and fades out at the sides (see globals.css); larger screens get
// the whole map. Both <Image>s are in the page and CSS shows one: the hidden
// one is display:none and lazy, so the browser never downloads it. The same
// trick on the wrapper hides the other theme's map.
// A tiny version of the map (generated by Next at build time, inlined in the
// page) shows until the map has loaded; scaled up, it reads as a soft blur.
// It's passed directly rather than as placeholder="blur": Next's blur effect
// makes the placeholder opaque, which turns the maps' transparent, faded
// edges into a grey box.
// The visible map is the largest element on screen (the LCP), hence high
// fetch priority.
function CityMap({ city, theme }: { city: CityData; theme: "light" | "dark" }) {
  const map = (variant: MapVariant, className: string) => {
    const image = mapImage(city, theme, variant);
    return (
      <Image
        {...image}
        alt=""
        fill
        placeholder={image.src.blurDataURL as `data:image/${string}`}
        loading="lazy"
        fetchPriority="high"
        // objectFit via style (not a class) so the blur placeholder is sized
        // the same way as the image.
        style={{ objectFit: variant === "mobile" ? "cover" : "contain" }}
        className={`map-fade-x pointer-events-none ${className}`}
      />
    );
  };
  return (
    <div className={`absolute inset-0 ${theme === "light" ? "dark:hidden" : "hidden dark:block"}`}>
      {map("mobile", "sm:hidden")}
      {map("desktop", "hidden sm:block")}
    </div>
  );
}

type Props = {
  city: CityData;
  direction: number;
  index: number;
  isFlipped: boolean;
  onSwipe: (step: 1 | -1) => void;
  onFlip: () => void;
};

export default function City({ city, direction, index, isFlipped, onSwipe, onFlip }: Props) {
  const isTouchDevice = useMediaQuery(TOUCH_DEVICE_QUERY);

  const handleDragEnd = (_: unknown, { offset, velocity }: PanInfo) => {
    if (offset.x < -SWIPE_DISTANCE || velocity.x < -SWIPE_VELOCITY) onSwipe(1);
    else if (offset.x > SWIPE_DISTANCE || velocity.x > SWIPE_VELOCITY) onSwipe(-1);
  };

  return (
    // select-none: double-clicking the ticket (to flip it twice) would
    // otherwise highlight the images as selected.
    <div className="relative flex min-h-[300px] w-full max-w-[902px] select-none flex-col items-center justify-center self-stretch overflow-hidden sm:min-h-[540px] sm:self-auto">
      {/* Both themes' maps are in the page and CSS shows the current one, so
          the right map is there on first paint (the theme class is set before
          the page renders). ImageGallery preloads the other theme's map when
          idle so a theme switch is instant; the switch itself is cross-faded
          by ThemeToggleButton. Keyed by city, so changing city cross-fades
          from the old map to the new one (mapVariants above). */}
      <AnimatePresence initial={false} custom={direction}>
        <motion.div
          key={city.city}
          custom={direction}
          variants={mapVariants}
          initial="enter"
          animate="center"
          exit="exit"
          transition={{ duration: 0.45, ease: [0.4, 0, 0.2, 1] }}
          className="pointer-events-none absolute inset-0"
        >
          <CityMap city={city} theme="light" />
          <CityMap city={city} theme="dark" />
        </motion.div>
      </AnimatePresence>

      {/* The ticket column fills the full height so a swipe anywhere on it
          (not only on the ticket itself) changes city. */}
      <div className="relative z-20 flex max-h-[760px] min-h-[200px] w-full max-w-[382px] flex-1 flex-col items-center justify-center px-4 sm:max-w-[350px] sm:px-0">
        <AnimatePresence initial={false} custom={direction} mode="wait">
          <motion.div
            key={index}
            custom={direction}
            variants={slideVariants}
            initial="enter"
            animate="center"
            exit="exit"
            transition={{
              x: { type: "spring", stiffness: 500, damping: 40 },
              opacity: { duration: 0.15 },
            }}
            // Swipe left/right on touch devices; vertical scrolling still works.
            drag={isTouchDevice ? "x" : false}
            dragConstraints={{ left: 0, right: 0 }}
            dragElastic={0.7}
            onDragEnd={handleDragEnd}
            className="flex w-full flex-1 items-center justify-center"
          >
            <Ticket city={city} isFirst={index === 0} isFlipped={isFlipped} onFlip={onFlip} />
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
}
